{{- if .Values.gateway.internal.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "awg-mainaccess.fullname" . }}-internal
  labels:
    {{- include "awg-mainaccess.labels" . | nindent 4 }}
  {{- with .Values.gateway.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.internal.className }}
  gatewayClassName: {{ . }}
  {{- end }}
  {{- range .Values.gateway.internal.hostnames }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: {{ . | quote }}
    allowedRoutes:
      namespaces:
        from: Same
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ include "awg-mainaccess.fullname" $ }}-internal-tls
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "awg-mainaccess.fullname" . }}-internal
  labels:
    {{- include "awg-mainaccess.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "awg-mainaccess.fullname" . }}-internal
  hostnames:
  {{- range .Values.gateway.internal.hostnames }}
    - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: {{ include "awg-mainaccess.component.fullname" (dict "componentName" "web" "context" $) }}
      port: 80
{{- end }}
