server:
  forward-headers-strategy: framework

management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          awg-mainaccess-web:
            require-authorization-consent: false
            registration:
              client-id: "awg-mainaccess-web"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:47740/oidc-callback"
              post-logout-redirect-uris:
                - "http://localhost:47740/oidc-signout-callback"
              scopes:
                - "openid"
                - "profile"
                - "email"
