server:
  forward-headers-strategy: framework
  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always  
  endpoints:
      web:
        exposure:
            include: '*'

conf:
  mainaccess:
    auth:
      oidc:
        authority: foo
        clientId: client_id
