server:
  port: 47740
  error:
    whitelabel:
      enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:47741/
          audiences: https://mainaccess.awginc.com

gg:
  jte:
    developmentMode: true

conf:
  mainaccess:
    auth:
      oidc:
        authority: http://localhost:47741/
        clientId: awg-mainaccess-web
        responseType: code
    apps:
      - name: Store Master
        targetUrl: http://localhost:47751/
      - name: Example 2
        targetUrl: http://localhost:47751/
      - name: Example 3
        targetUrl: http://localhost:47751/
      - name: Example 4
        targetUrl: http://localhost:47751/
