server:
  port: 47740
  error:
    whitelabel:
      enabled: false

gg:
  jte:
    developmentMode: true

conf:
  mainaccess:
    auth:
      oidc:
        authority: http://localhost:47741/
        clientId: awg-mainaccess-web
        responseType: code
