server:
  forward-headers-strategy: framework

management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always  
  endpoints:
      web:
        exposure:
            include: '*'
conf:
  servicebus:
    endpoint: ${CONF_SERVICEBUS_ENDPOINT}
