export const US_STATES = [
    { id: 'AL', display: 'Alabama' },
    { id: 'AK', display: 'Alaska' },
    { id: 'AZ', display: 'Arizona' },
    { id: 'AR', display: 'Arkansas' },
    { id: 'CA', display: 'California' },
    { id: 'CO', display: 'Colorado' },
    { id: 'CT', display: 'Connecticut' },
    { id: 'DE', display: 'Delaware' },
    { id: 'FL', display: 'Florida' },
    { id: 'GA', display: 'Georgia' },
    { id: 'HI', display: 'Hawaii' },
    { id: 'ID', display: 'Idaho' },
    { id: 'IL', display: 'Illinois' },
    { id: 'IN', display: 'Indiana' },
    { id: 'IA', display: 'Iowa' },
    { id: 'KS', display: 'Kansas' },
    { id: 'KY', display: 'Kentucky' },
    { id: 'LA', display: 'Louisiana' },
    { id: 'ME', display: 'Maine' },
    { id: 'MD', display: 'Maryland' },
    { id: 'MA', display: 'Massachusetts' },
    { id: 'MI', display: 'Michigan' },
    { id: 'MN', display: 'Minnesota' },
    { id: 'MS', display: 'Mississippi' },
    { id: 'MO', display: 'Missouri' },
    { id: 'MT', display: 'Montana' },
    { id: 'NE', display: 'Nebraska' },
    { id: 'NV', display: 'Nevada' },
    { id: 'NH', display: 'New Hampshire' },
    { id: 'NJ', display: 'New Jersey' },
    { id: 'NM', display: 'New Mexico' },
    { id: 'NY', display: 'New York' },
    { id: 'NC', display: 'North Carolina' },
    { id: 'ND', display: 'North Dakota' },
    { id: 'OH', display: 'Ohio' },
    { id: 'OK', display: 'Oklahoma' },
    { id: 'OR', display: 'Oregon' },
    { id: 'PA', display: 'Pennsylvania' },
    { id: 'RI', display: 'Rhode Island' },
    { id: 'SC', display: 'South Carolina' },
    { id: 'SD', display: 'South Dakota' },
    { id: 'TN', display: 'Tennessee' },
    { id: 'TX', display: 'Texas' },
    { id: 'UT', display: 'Utah' },
    { id: 'VT', display: 'Vermont' },
    { id: 'VA', display: 'Virginia' },
    { id: 'WA', display: 'Washington' },
    { id: 'WV', display: 'West Virginia' },
    { id: 'WI', display: 'Wisconsin' },
    { id: 'WY', display: 'Wyoming' },
];
