name: awg-mainaccess

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool && ln -s `which dotnet-gitversion` /usr/local/bin/gitversion && gitversion

    - name: Build with Gradle Wrapper
      run: ./gradlew dist

    - name: Upload Dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
      
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool && ln -s `which dotnet-gitversion` /usr/local/bin/gitversion && gitversion

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
